name: First WorkFlow
on: workflow_dispatch 
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: | 
          echo "Hello World First!"
          echo "Hello World Second!"
      - name: Print Goodbye
        run: echo "Done - Bye" 
      
